# Generated by Django 4.2.1 on 2025-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (кол-во мест)')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя (л.с.)')),
            ],
        ),
    ]
