# Generated by Django 5.1.4 on 2025-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airport_alter_airplane_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.AddField(
            model_name='airplane',
            name='consumption',
            field=models.PositiveIntegerField(default=8000, verbose_name='Расход топлива (кг/час)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='cruise_speed',
            field=models.PositiveIntegerField(default=1000, verbose_name='Крейсерская скорость (км/час)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_distance',
            field=models.PositiveIntegerField(default=6000, verbose_name='Максимальное расстояние (км)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='name',
            field=models.CharField(default='Boeing', max_length=50, verbose_name='Название самолета'),
        ),
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='IATA код'),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(default='NameOfAirport', max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость пассажиров'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
