# Generated by Django 5.2.1 on 2025-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airport_alter_airplane_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='consumption',
            field=models.IntegerField(default=8000, verbose_name='Расход топлива (кг/час)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='name',
            field=models.CharField(default='Boeing', max_length=50, verbose_name='Название самолета'),
        ),
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='IATA код'),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='airport',
            name='rus_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город НА РУССКОМ'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость пассажиров'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
