# Generated by Django 5.2.1 on 2025-05-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airplane_consumption_airplane_name_airport_iata_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='rus_city',
        ),
    ]
