# Generated by Django 5.2.1 on 2025-05-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_airport_rus_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(default='NameOfAirport', max_length=100, verbose_name='название'),
        ),
    ]
