# Generated by Django 5.1.4 on 2025-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_airport_city_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='cruise_speed',
            field=models.PositiveIntegerField(default=1000, verbose_name='Крейсерская скорость (км/час)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='max_distance',
            field=models.PositiveIntegerField(default=6000, verbose_name='Максимальное расстояние (км)'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='consumption',
            field=models.PositiveIntegerField(default=8000, verbose_name='Расход топлива (кг/час)'),
        ),
    ]
