# Generated by Django 4.2.1 on 2025-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_airplane_cruise_speed_airplane_max_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='airport',
            name='description',
            field=models.CharField(default='No description', max_length=500, verbose_name='Описание'),
        ),
    ]
