# Generated by Django 4.2.1 on 2025-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_airplane_description_airport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_plane_photo/', verbose_name='Фото самолета'),
        ),
    ]
