# Generated by Django 4.2.1 on 2025-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_airplane_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='in_service',
            field=models.BooleanField(default=True, verbose_name='В эксплуатации'),
        ),
    ]
