# Generated by Django 5.2.17 on 2026-09-25 12:27

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_airplane_in_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={
                "ordering": ["name"],
                "verbose_name": "самолёт",
                "verbose_name_plural": "самолёты",
            },
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={
                "ordering": ["name"],
                "verbose_name": "аэропорт",
                "verbose_name_plural": "аэропорты",
            },
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="engine_power",
        ),
        migrations.AddField(
            model_name="airplane",
            name="engines",
            field=models.CharField(
                blank=True,
                help_text="Например: 2 × CFM56-7B",
                max_length=120,
                verbose_name="Двигатели",
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Пассажировместимость"
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="consumption",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Расход топлива, кг/ч",
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="cruise_speed",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Крейсерская скорость, км/ч",
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="airplanes/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="max_distance",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Максимальная дальность, км",
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="year_of_manufacture",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Год выпуска"
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(
                max_length=3,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}$", "IATA-код — три латинские буквы, например SVO."
                    )
                ],
                verbose_name="IATA-код",
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(
                fields=["country"], name="core_airpor_country_7ff515_idx"
            ),
        ),
    ]
